server:
  port: 8081
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3307/lc_plateform
    username: root
    password: 666888
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    ## Redis 配置
  redis:
  ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
    ## 连接池最大连接数（使用负值表示没有限制）
        max-active: 9
    ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ## 连接池中的最大空闲连接
        max-idle: 8
        ## 连接池中的最小空闲连接
        min-idle: 0

        ## 连接超时时间（毫秒）
    timeout: 5000
mybatis:
  typeAliasesPackage: com.lacForever.model
  mapperLocations: classpath:mapper/*.xml
